# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog_3(object):

    def setupUi(self, Dialog):

        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)

        self.widget = QtWidgets.QWidget(parent=Dialog)

        self.widget.setGeometry(QtCore.QRect(0, 0, 1200, 811))

        self.widget.setStyleSheet("QWidget#widget{\n"
                                  "background-color:qlineargradient("
                                  "spread:pad,"
                                  " x1:0.0101244"
                                  ", y1:0,"
                                  " x2:0.71592,"
                                  " y2:0.875,"
                                  " stop:0 rgba(0, 0, 255, 255),"
                                  " stop:1 rgba(255, 85, 0, 255))}")

        self.widget.setObjectName("widget")

        self.label = QtWidgets.QLabel(parent=self.widget)

        self.label.setGeometry(QtCore.QRect(410, 140, 391, 81))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";\n"
                                 "color:rgb(255, 255, 255)")

        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(parent=self.widget)

        self.label_2.setGeometry(QtCore.QRect(360, 250, 511, 61))
        self.label_2.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";\n"
                                   "color:rgb(255, 255, 255)")

        self.label_2.setObjectName("label_2")

        self.pushButton = QtWidgets.QPushButton(parent=self.widget)

        self.pushButton.setGeometry(QtCore.QRect(470, 360, 281, 61))
        self.pushButton.setStyleSheet("border-radius:20px;\n"
                                      "color:rgb(0, 0, 0);\n"
                                      "background-color:rgb(0, 238, 238);\n"
                                      "font: 14pt \"MS Shell Dlg 2\";")

        self.pushButton.setObjectName("pushButton")

        self.hesapolustur = QtWidgets.QPushButton(parent=self.widget)

        self.hesapolustur.setGeometry(QtCore.QRect(470, 460, 281, 61))
        self.hesapolustur.setStyleSheet("border-radius:20px;\n"
                                        "color:rgb(0, 0, 0);\n"
                                        "background-color:rgb(0, 238, 238);\n"
                                        "font: 14pt \"MS Shell Dlg 2\";")

        self.hesapolustur.setObjectName("hesapolustur")

        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget)

        self.pushButton_2.setGeometry(QtCore.QRect(570, 620, 93, 28))
        self.pushButton_2.setStyleSheet("border-radius:7px;\n"
                                        "color:rgb(0, 0, 0);\n"
                                        "background-color:rgb(0, 238, 238);\n"
                                        "font: 12px \"MS Shell Dlg 2\";")

        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):

        _translate = QtCore.QCoreApplication.translate

        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.label.setText(_translate("Dialog", "Добрый день"))
        self.label_2.setText(_translate("Dialog", "ЗАРЕГИСТРИРУЙТЕСЬ И СОЗДАЙТЕ НОВЫЙ АККАУНТ"))
        self.pushButton.setText(_translate("Dialog", "ВХОД"))
        self.hesapolustur.setText(_translate("Dialog", "ЗАРЕГИСТРИРОВАТЬСЯ"))
        self.pushButton_2.setText(_translate("Dialog", "ВЫХОД"))
